'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LlamaCppServerLauncher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Advanced Sampling 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AdvancedSamplingExpander() As String
            Get
                Return ResourceManager.GetString("AdvancedSamplingExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Advanced Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AdvancedSettingsTabHeader() As String
            Get
                Return ResourceManager.GetString("AdvancedSettingsTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 All Categories 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AllCategories() As String
            Get
                Return ResourceManager.GetString("AllCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 All Categories 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AllCategoriesLabel() As String
            Get
                Return ResourceManager.GetString("AllCategoriesLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 LLaMA.cpp HTTP Server Launcher 的本地化字符串。
        '''</summary>
        Public ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Basic Parameters 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BasicParametersExpander() As String
            Get
                Return ResourceManager.GetString("BasicParametersExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Basic Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BasicSettingsTabHeader() As String
            Get
                Return ResourceManager.GetString("BasicSettingsTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Batch Threads: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BatchThreadsLabel() As String
            Get
                Return ResourceManager.GetString("BatchThreadsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Browse... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property BrowseButton() As String
            Get
                Return ResourceManager.GetString("BrowseButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ClearButton() As String
            Get
                Return ResourceManager.GetString("ClearButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear Filters 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ClearFiltersButton() As String
            Get
                Return ResourceManager.GetString("ClearFiltersButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear Output 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ClearOutputButton() As String
            Get
                Return ResourceManager.GetString("ClearOutputButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Command copied to clipboard 的本地化字符串。
        '''</summary>
        Public ReadOnly Property CommandCopied() As String
            Get
                Return ResourceManager.GetString("CommandCopied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Command Preview 的本地化字符串。
        '''</summary>
        Public ReadOnly Property CommandPreviewTabHeader() As String
            Get
                Return ResourceManager.GetString("CommandPreviewTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Context Size: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ContextSizeLabel() As String
            Get
                Return ResourceManager.GetString("ContextSizeLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Copy to Clipboard 的本地化字符串。
        '''</summary>
        Public ReadOnly Property CopyCommandButton() As String
            Get
                Return ResourceManager.GetString("CopyCommandButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 CPU and Thread Management 的本地化字符串。
        '''</summary>
        Public ReadOnly Property CpuThreadManagementExpander() As String
            Get
                Return ResourceManager.GetString("CpuThreadManagementExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Default Parameters: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property DefaultParametersLabel() As String
            Get
                Return ResourceManager.GetString("DefaultParametersLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error loading settings: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorLoadingSettings() As String
            Get
                Return ResourceManager.GetString("ErrorLoadingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please specify the model file path 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorModelPathRequired() As String
            Get
                Return ResourceManager.GetString("ErrorModelPathRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error saving settings: {0} 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorSavingSettings() As String
            Get
                Return ResourceManager.GetString("ErrorSavingSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please specify the server executable path 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ErrorServerPathRequired() As String
            Get
                Return ResourceManager.GetString("ErrorServerPathRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable Flash Attention 的本地化字符串。
        '''</summary>
        Public ReadOnly Property FlashAttentionCheckBox() As String
            Get
                Return ResourceManager.GetString("FlashAttentionCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Frequency Penalty: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property FrequencyPenaltyLabel() As String
            Get
                Return ResourceManager.GetString("FrequencyPenaltyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Generated Command Line: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property GeneratedCommandLineLabel() As String
            Get
                Return ResourceManager.GetString("GeneratedCommandLineLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 GPU Layers: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property GpuLayersLabel() As String
            Get
                Return ResourceManager.GetString("GpuLayersLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Host: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property HostLabel() As String
            Get
                Return ResourceManager.GetString("HostLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Use unified KV buffer 的本地化字符串。
        '''</summary>
        Public ReadOnly Property KVUnifiedCheckBox() As String
            Get
                Return ResourceManager.GetString("KVUnifiedCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 中文 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageChinese() As String
            Get
                Return ResourceManager.GetString("LanguageChinese", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 English 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageEnglish() As String
            Get
                Return ResourceManager.GetString("LanguageEnglish", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Language: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LanguageLabel() As String
            Get
                Return ResourceManager.GetString("LanguageLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Load Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LoadSettingsButton() As String
            Get
                Return ResourceManager.GetString("LoadSettingsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable log colors 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LogColorsCheckBox() As String
            Get
                Return ResourceManager.GetString("LogColorsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Logging and Monitoring 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LoggingExpander() As String
            Get
                Return ResourceManager.GetString("LoggingExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable log timestamps 的本地化字符串。
        '''</summary>
        Public ReadOnly Property LogTimestampsCheckBox() As String
            Get
                Return ResourceManager.GetString("LogTimestampsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Memory Management 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MemoryManagementExpander() As String
            Get
                Return ResourceManager.GetString("MemoryManagementExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable metrics endpoint 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MetricsCheckBox() As String
            Get
                Return ResourceManager.GetString("MetricsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Min P: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MinPLabel() As String
            Get
                Return ResourceManager.GetString("MinPLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Force model in RAM (mlock) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property MlockCheckBox() As String
            Get
                Return ResourceManager.GetString("MlockCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Model Path: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ModelPathLabel() As String
            Get
                Return ResourceManager.GetString("ModelPathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Modified Parameters: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ModifiedParametersLabel() As String
            Get
                Return ResourceManager.GetString("ModifiedParametersLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Network Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NetworkSettingsExpander() As String
            Get
                Return ResourceManager.GetString("NetworkSettingsExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Disable KV offload 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoKVOffloadCheckBox() As String
            Get
                Return ResourceManager.GetString("NoKVOffloadCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Don&apos;t memory-map model 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoMmapCheckBox() As String
            Get
                Return ResourceManager.GetString("NoMmapCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Disable weight repacking 的本地化字符串。
        '''</summary>
        Public ReadOnly Property NoRepackCheckBox() As String
            Get
                Return ResourceManager.GetString("NoRepackCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Open Browser 的本地化字符串。
        '''</summary>
        Public ReadOnly Property OpenBrowserButton() As String
            Get
                Return ResourceManager.GetString("OpenBrowserButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Showing {0} / {1} parameters 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ParameterCountText() As String
            Get
                Return ResourceManager.GetString("ParameterCountText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameter List 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ParameterListHeader() As String
            Get
                Return ResourceManager.GetString("ParameterListHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameter Statistics 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ParameterStatisticsHeader() As String
            Get
                Return ResourceManager.GetString("ParameterStatisticsHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Port: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PortLabel() As String
            Get
                Return ResourceManager.GetString("PortLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Presence Penalty: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property PresencePenaltyLabel() As String
            Get
                Return ResourceManager.GetString("PresencePenaltyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Repeat Penalty: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property RepeatPenaltyLabel() As String
            Get
                Return ResourceManager.GetString("RepeatPenaltyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sampling Parameters 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SamplingParametersExpander() As String
            Get
                Return ResourceManager.GetString("SamplingParametersExpander", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Sampling Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SamplingSettingsTabHeader() As String
            Get
                Return ResourceManager.GetString("SamplingSettingsTabHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save Settings 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SaveSettingsButton() As String
            Get
                Return ResourceManager.GetString("SaveSettingsButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Search parameter names, descriptions, categories... (supports Chinese and English) 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SearchWatermark() As String
            Get
                Return ResourceManager.GetString("SearchWatermark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [info] Server manually stopped 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerManuallyStopped() As String
            Get
                Return ResourceManager.GetString("ServerManuallyStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Output 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerOutputHeader() As String
            Get
                Return ResourceManager.GetString("ServerOutputHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Path: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerPathLabel() As String
            Get
                Return ResourceManager.GetString("ServerPathLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Running 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerStatusRunning() As String
            Get
                Return ResourceManager.GetString("ServerStatusRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Starting... 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerStatusStarting() As String
            Get
                Return ResourceManager.GetString("ServerStatusStarting", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Server Status: Stopped 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ServerStatusStopped() As String
            Get
                Return ResourceManager.GetString("ServerStatusStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Settings loaded successfully 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SettingsLoaded() As String
            Get
                Return ResourceManager.GetString("SettingsLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Settings saved successfully 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SettingsSaved() As String
            Get
                Return ResourceManager.GetString("SettingsSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Show modified parameters only 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ShowModifiedOnlyLabel() As String
            Get
                Return ResourceManager.GetString("ShowModifiedOnlyLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Enable slots endpoint 的本地化字符串。
        '''</summary>
        Public ReadOnly Property SlotsCheckBox() As String
            Get
                Return ResourceManager.GetString("SlotsCheckBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start Server 的本地化字符串。
        '''</summary>
        Public ReadOnly Property StartServerButton() As String
            Get
                Return ResourceManager.GetString("StartServerButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Server 的本地化字符串。
        '''</summary>
        Public ReadOnly Property StopServerButton() As String
            Get
                Return ResourceManager.GetString("StopServerButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Temperature: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TemperatureLabel() As String
            Get
                Return ResourceManager.GetString("TemperatureLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Threads: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property ThreadsLabel() As String
            Get
                Return ResourceManager.GetString("ThreadsLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Timeout (s): 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TimeoutLabel() As String
            Get
                Return ResourceManager.GetString("TimeoutLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Top K: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TopKLabel() As String
            Get
                Return ResourceManager.GetString("TopKLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Top P: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TopPLabel() As String
            Get
                Return ResourceManager.GetString("TopPLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Total Parameters: 的本地化字符串。
        '''</summary>
        Public ReadOnly Property TotalParametersLabel() As String
            Get
                Return ResourceManager.GetString("TotalParametersLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Update Command Preview 的本地化字符串。
        '''</summary>
        Public ReadOnly Property UpdateCommandPreviewButton() As String
            Get
                Return ResourceManager.GetString("UpdateCommandPreviewButton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Verbose logging 的本地化字符串。
        '''</summary>
        Public ReadOnly Property VerboseCheckBox() As String
            Get
                Return ResourceManager.GetString("VerboseCheckBox", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
